name:         htgen
version:      0.0.5+3
description:  Functions for generating HTML
homepage:     https://github.com/bergwerf/htgen
environment:
  sdk:        '>=2.0.0-dev <3.0.0'

dev_dependencies:
  test: any
  build_runner: any
  build_web_compilers: any
