name:         htgen
version:      0.0.2+1
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Functions for generating HTML
homepage:     https://github.com/hermanbergwerf/htgen
environment:
  sdk:        '>=1.8.0 <2.0.0'
dev_dependencies:
  test:       ^0.12.20+13
  browser:    ^0.10.0+2
