name:         htgen
version:      0.0.3
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Functions for generating HTML
homepage:     https://github.com/bergwerf/htgen
environment:
  sdk:        '>=2.0.0-dev <3.0.0'

dev_dependencies:
  test: ^1.3.0
  build_runner: any
  build_web_compilers: any

